#!/usr/bin/sh

#####
if /usr/bin/tty -s ; then
    echo "${0} interactive shell, using stdout"
else
    exec 0</dev/null
    exec>>/root/d4c/appd.log 2>&1
fi
####


if killall -TERM appd.sh
then
    (echo -n "!!! $0 killed appd.sh "; date) #>> /root/d4c/appd.log
else
    (echo -n "!!! $0 FAILED to kill appd.sh "; date) #>> /root/d4c/appd.log
fi
    
if killall -TERM python
then
    (echo -n "!!! $0 killed python "; date) #>> /root/d4c/appd.log
else
    (echo -n "!!! $0 FAILED to kill python "; date) #>> /root/d4c/appd.log
fi

# use it with olinuxino, to make sure 5V reset will be introduced if 0xFEED fails
