#!/usr/bin/sh

#####
if /usr/bin/tty -s ; then
    echo "${0} interactive shell, using stdout"
else
    exec 0</dev/null
    exec>>/root/d4c/appd.log 2>&1
fi
####
	    
if killall -TERM openvpn
then
  echo vpn stopped
  exit 0
else
  echo stopping vpn failed...
  exit 1
fi
